### ISSUE TITLE
Error when running python script

### ISSUE THREAD

**Issue by Bilger321** [mechkeys/mechkeys#7]
When running the python script via command line to generate a KiCAD file, I get the following error:
```
Traceback (most recent call last):
  File "layout.py", line 885, in <module>
    main()
  File "layout.py", line 848, in main
    switch_sch.write(schem_template_header)
UnboundLocalError: local variable 'switch_sch' referenced before assignment
```

A project folder is generated, but with nothing inside of it.

Windows 10, Python v. 2.7.1.

**Comment by scott-t-wilson** [comment]
Fixed in 6920e4d
